---
name: metrics-demo

director_uuid: <%= `bosh status --uuid` %>

releases:
- name: metrics-demo
  version: latest
- name: cf
  version: latest

jobs:
- name: redis
  instances: 1
  resource_pool: metrics-demo
  networks:
  - name: default
  templates:
  - name: redis
    release: metrics-demo
  - name: emitter
    release: metrics-demo
  - name: consumer
    release: metrics-demo
  - name: metron_agent
    release: cf
  properties:
    metron_agent:
      zone: z1
      debug: false

networks:
- name: default
  subnets:
<% (0..28).each_with_index do |i| %>
  - range: 10.244.0.<%= i*4 %>/30
    reserved:
      - 10.244.0.<%= i*4 + 1 %>
    static:
      - 10.244.0.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>
<% (29..61).each_with_index do |i| %>
  - range: 10.244.0.<%= i*4 %>/30
    reserved:
      - 10.244.0.<%= i*4 + 1 %>
    cloud_properties:
      name: random
<% end %>
<% (62..63).each_with_index do |i| %>
  - range: 10.244.0.<%= i*4 %>/30
    reserved:
      - 10.244.0.<%= i*4 + 1 %>
    static:
      - 10.244.0.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>

resource_pools:
- name: metrics-demo
  network: default
  cloud_properties: {}
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

compilation:
  workers: 1
  network: default
  cloud_properties: {}

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

properties:
  loggregator:
    servers:
      z1: # A list of loggregator servers for every redundancy zone
      - 10.244.0.146
    incoming_port: 3456
    outgoing_port: 8080

  loggregator_endpoint: # The end point sources will connect to
    shared_secret: PLACEHOLDER-LOGGREGATOR-SECRET  
    host: 10.244.0.146
    port: 3456

  metron_agent:
    deployment: cf-warden

  metron_endpoint:
    shared_secret: PLACEHOLDER-LOGGREGATOR-SECRET

  etcd:
    machines:
    - 10.244.0.42

  nats:
    address: 10.244.0.6
    debug: false
    machines:
    - 10.244.0.6
    monitor_port: 4221
    password: nats
    port: 4222
    prof_port: 0
    trace: false
    user: nats